services:
  vote:
    build: 
      context: ./vote
      target: dev
    depends_on:
      redis:
        condition: service_healthy
    volumes:
     - ./vote:/usr/local/app
    ports:
      - "5000:80"
    networks:
      - back-tier

  redis:
    build: 
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - "./healthchecks:/healthchecks"
    networks:
      - back-tier

networks:
  back-tier: