services:
  vote:
    build: 
      context: ./vote
    depends_on:
      redis:
        condition: service_healthy
    volumes:
     - ./vote:/usr/local/app
    ports:
      - "5000:80"
    networks:
      - back-tier

  redis:
    build: 
      context: ./redis
    volumes:
      - "./healthchecks:/healthchecks"
    networks:
      - back-tier

networks:
  back-tier: